### ISSUE TITLE
Function `insert` is missing from the `Wrapping` behaviour

### ISSUE THREAD

**Issue by jtroo** [andylokandy/arraydeque#20]
I couldn't find any reason for this to be the case in the documentation or the issue tracker, so I'm guessing it got missed? If there **is** a reason that `insert` is missing for the `Wrapping` behaviour, it would be good to add it to the docs.

**Comment by andylokandy** [comment]
I apologize for the delayed response. I missed the notification and am only just now getting back to you. The missing `inesrt`  is intentional. The reason for this is that it's undecided which side of the element should be popped when the deque is full.

Think of a deque `[a, b]` whose capacity is 2:

```
   a      b
^     ^      ^
0     1      2
```

insert an element to index 2 is the same as to index 0, therefore popping `a` or `b` could both be reasonable.
