### ISSUE TITLE
Overwriting API variants

### ISSUE THREAD

**Issue by regexident** [andylokandy/arraydeque#6]
Hi Andy,

I found **arraydeque** while looking for a stack-allocated fixed-size circular buffer that is compatible with `no_std`.

It seems to match 90% of my (DSP-related) needs, but seems to lack support for overwriting existing elements rather than dropping a given insert.

I'd rather not implement my own circular buffer from scratch, so I chose to –for now– just extend its existing API through a trait:

```rust
trait WrapAround {
    type Item;

    fn wrapping_push_back(&mut self, item: Self::Item) -> Option<Self::Item>;
    fn wrapping_push_front(&mut self, item: Self::Item) -> Option<Self::Item>;
}

impl<T> WrapAround for ArrayDeque<T> where T: Array {
    type Item = T::Item;

    fn wrapping_push_back(&mut self, item: Self::Item) -> Option<Self::Item> {
        let existing = if self.len() == self.capacity() {
            self.pop_front()
        } else {
            None
        };
        self.push_back(item);
        existing
    }

    fn wrapping_push_front(&mut self, item: Self::Item) -> Option<Self::Item> {
        let existing = if self.len() == self.capacity() {
            self.pop_back()
        } else {
            None
        };
        self.push_front(item);
        existing
    }
}
```

I'm certainly not the only one with these particular needs (especially with Rust reaching for a wide use in embedded/DSP). And there are a bunch of other methods on `ArrayDeque<T>` that would make sense to provide "wrapping" variants for.

So, should I:

1. Create my own MIT-licensed crate under a different name by copying your code but changing its logic from "drop if full" to "overwrite if full"?
2. Make a PR for **arraydeque** adding `wrapping_`-variants (or whatever prefix seems most appropriate) to all methods that would make sense?
3. Make a PR for **arraydeque** adding a `overwriting: bool` field to `ArrayDeque<T>` (along with setter & getter), which would then change the behavior of the existing API?
4. Make a PR for **arraydeque** adding a `Wrapping<T>` wrapper for `ArrayDeque<T>`, which would then change the behavior of the wrapped deque's API?

?

1. would cause needless duplication. 
2. would clutter the API.
3. would make the API depend on the state of `self.overwriting`.
4. would probably be the cleanest approach?

**Comment by andylokandy** [comment]
Hi regexiden,
Thank you for spending time writing up this issue. For a long time, `arraydeque` lacks the ability to automatically removes elements when attempting to insert when full, overwriting, in your words. This is an know problem, which I've tried to solve before. There are already an obsolete issue opened and also a pull request focus on and try to solve this issue.

We previously hit on some problems, which you've mentioned.
- Code duplication
- Bloated API

And more
- Behavior of Trait `Extend`, `FromIterator`
- May cause breaking changes

I postponed because it's not clear where `arraydeque` would be used at that time, and `arrayvec` was approximating huge changes on API, from which `arraydeque` learns.

I think it's time to refocus on this now, since `arrayvec` have stabilized new API, and the most importantly, it's quite clear that `arraydeque` needs this feature, not only embedded devices but Servo. So I will work actively these two weeks until `arraydeque` moves to new API and accepts ’overwriting’ feature. 

As the constrains, there are only three viable options.
- New type `ArrayDequeWrapping<[T; N]>`
- Add a type parameter on `ArrayDeuqe`, determining whether to enable wrapping behavior, which would look like `ArrayDeque<[usize; 64], Wrapping>`, which disabled as default.
- Add a type wrapper, you proposed, `Wrapping<ArrayDeque<T; N>>`.

Personally, I dislike the first idea, and I may pick one of the last two.

**Comment by andylokandy** [comment]
I'm doing some code cleaning staff. New version may be published in these days. 

Currently, I removed `.append()` and `.prepend()` because:

- `extend_*()` methods are more generic and cover append's functionality.
- It's literally vague whichever side `.append()` applies on.

I replaced macro in test code with generic functions.

Also, I discovered a memory safety issue on new wrapping behavior, which would only appear in a corner case: zero-capacity. Our code previsouly assumed `.pop()` always spare space and perform unchecked push directly, and we now know it's not hold.

**Comment by regexident** [comment]
> I'm doing some code cleaning staff. New version may be published in these days.

Cool!

> Currently, I removed .append() and .prepend() because:
> 
> - `extend_*()` methods are more generic and cover append's functionality.
> - It's literally vague whichever side `.append()` applies on.

Yes. Also `.prepend()` and `.extend_front()` subtly differ in the order of extended elements.

> I replaced macro in test code with generic functions.

Good one. I should have used those to begin with!

> Also, I discovered a memory safety issue on new wrapping behavior, which would only appear in a corner case: zero-capacity. Our code previsouly assumed `.pop()` always spare space and then perform unchecked push directly, and we now know it's not hold.

Good catch. How would you want to fix this?

My gut feeling is that extending a zero-capacity deque is enough of a edge-case to just make it panic, as it's clearly a programmer error, not a runtime error.

**Comment by andylokandy** [comment]
> Good catch. How would you want to fix this?

I tend not to panic but drop-in-place the inserting element. This should be no performance overhead after complier optimization.

**Comment by regexident** [comment]
Sounds good to me.

**Comment by andylokandy** [comment]
Replaced `.wrapping()` and `.saturating()` with `From` impls.

**Comment by andylokandy** [comment]
Removing `.insert()` from `Wrapping` because:
- Indexing issue. Popping from front when full will change the index of all elements, while there are no way to insert an element into last index if we pop from back when full(or rewrite `insert_unchecked`).
- Arbitrary popping side would not make sense.

**Comment by andylokandy** [comment]
v0.3.1 released! 😆 🎉

**Comment by andylokandy** [comment]
Thank you @regexident

**Comment by regexident** [comment]
Awesome, thanks!

**Comment by andylokandy** [comment]
v0.4.1 is also released to resolve capacity inconsistency.
